name: Continuous Integration

on:
  pull_request:
    branches: [ mainline ]
  push:
    branches: [ mainline ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>trjohnny</username><password>${{env.GITHUB_TOKEN}}</password></server></servers></settings>" > ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Build all Maven projects
        run: |
          find . -name pom.xml -not -path "*/target/*" | while read pom; do
            dir=$(dirname "$pom")
            echo "Building Maven project in '$dir'"
            (cd "$dir" && mvn -B package --settings ~/.m2/settings.xml)
          done
